version: "3.9"

services:
  aws-credential-service:
    build:
      context: ./AwsCredentialsService
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    volumes:
      - $AWS_FILE_PATH:/app/aws
