version: "3.9"

services:
    aws-credential-service:
        build:
            context: ./service
            dockerfile: Dockerfile
        ports:
            - 50173:80
        restart: always
        volumes:
            - ~/.aws/:/app/aws
